/**
 * Static seed (TRD §12). Idempotent: every write is an upsert on a natural key, so it is safe to
 * run on every deploy. The rolling demo orders are generated by the API itself (P10).
 *
 * Run: pnpm --filter @fernleaf/backend db:seed
 */
import 'dotenv/config';
import { PrismaPg } from '@prisma/adapter-pg';
import { PrismaClient } from '../../src/generated/prisma/client';
import { seedAccess } from './access';
import { seedPlatform } from './platform';

async function main(): Promise<void> {
  const url = process.env.DIRECT_DATABASE_URL ?? process.env.DATABASE_URL;
  if (!url) throw new Error('Set DIRECT_DATABASE_URL (or DATABASE_URL) to seed.');
  const prisma = new PrismaClient({ adapter: new PrismaPg({ connectionString: url }) });

  try {
    const started = Date.now();
    await seedPlatform(prisma);
    await seedAccess(prisma);
    console.log(`Seed complete in ${Date.now() - started} ms`);
  } finally {
    await prisma.$disconnect();
  }
}

main().catch((error: unknown) => {
  console.error(error);
  process.exit(1);
});
